### ISSUE TITLE
The PDOK location server has changed it's url, this package is no longer working.

### ISSUE THREAD

**Issue by BadRookiDev** [chabter/laravel-dutch-postalcode-lookup#2]
Since today the old URL's to the location server API are removed. 
https://www.pdok.nl/-/migratie-pdok-locatieserver-naar-het-nieuwe-3g-platform-afgerond

Can you please update the version of this dependency:
https://github.com/swisnl/geocoder-php-nationaal-georegister-provider

**Comment by GekkeGeneraal** [comment]
We're sorry for the delay! We have updated the dependencies and the package is working again.
